# 31 Entity Disambiguation

Phase 31 execution notebook for layered entity disambiguation restart.

The notebook orchestrates the pipeline in separate phase cells so each stage can be debugged independently.

This notebook performs one deterministic automated run and writes aligned artifacts for manual downstream reconciliation.

In [1]:
from pathlib import Path
from datetime import UTC, datetime
import os
import sys

import pandas as pd

repo_root = Path.cwd()
if not (repo_root / "speakermining").exists():
    # Notebook may be opened from the notebooks folder.
    for parent in [repo_root] + list(repo_root.parents):
        if (parent / "speakermining").exists():
            repo_root = parent
            break

os.chdir(repo_root)
src_path = repo_root / "speakermining" / "src"
if str(src_path) not in sys.path:
    sys.path.insert(0, str(src_path))


from process.entity_disambiguation.contracts import INPUT_FILES
from process.entity_disambiguation.orchestrator import build_source_inventory_report
from process.io_guardrails import atomic_write_csv


CLASS_SOURCE_PLANS: dict[str, list[tuple[str, str | None]]] = {
    "broadcasting_programs": [
        ("setup", "setup_broadcasting_programs"),
        ("wikidata", "wikidata_programs"),
        ("fernsehserien_de", None),
    ],
    "seasons": [
        ("zdf_archive", "zdf_seasons"),
        ("wikidata", "wikidata_series"),
        ("fernsehserien_de", None),
    ],
    "episodes": [
        ("zdf_archive", "zdf_episodes"),
        ("wikidata", "wikidata_episodes"),
        ("fernsehserien_de", "fs_episode_metadata"),
    ],
    "persons": [
        ("zdf_archive", "zdf_persons"),
        ("wikidata", "wikidata_persons"),
        ("fernsehserien_de", "fs_episode_guests"),
    ],
    "topics": [
        ("zdf_archive", "zdf_topics"),
        ("wikidata", "wikidata_topics"),
        ("fernsehserien_de", None),
    ],
    "roles": [
        ("zdf_archive", "zdf_persons"),
        ("wikidata", "wikidata_roles"),
        ("fernsehserien_de", None),
    ],
    "organizations": [
        ("zdf_archive", None),
        ("wikidata", "wikidata_organizations"),
        ("fernsehserien_de", None),
    ],
}


def write_example(df: pd.DataFrame, out_path: Path) -> None:
    from process.io_guardrails import atomic_write_csv

    out_path.parent.mkdir(parents=True, exist_ok=True)
    atomic_write_csv(out_path, df.head(1), index=False)


def _class_inventory_rows(class_name: str) -> pd.DataFrame:
    rows: list[dict[str, str | int]] = []
    plan = CLASS_SOURCE_PLANS.get(class_name, [])
    for source_label, source_key in plan:
        if source_key is None:
            rows.append({"source": source_label, "instances": "n.a.", "properties": "n.a."})
            continue

        if source_key not in source_inventory.index:
            rows.append({"source": source_label, "instances": "n.a.", "properties": "n.a."})
            continue

        rows.append(
            {
                "source": source_label,
                "instances": int(source_inventory.loc[source_key, "instances"]),
                "properties": int(source_inventory.loc[source_key, "properties"]),
            }
        )

    return pd.DataFrame(rows)


def print_alignment_progress(class_name: str, frame: pd.DataFrame) -> pd.DataFrame:
    class_inventory = _class_inventory_rows(class_name)
    unresolved = int(frame["match_tier"].eq("unresolved").sum()) if "match_tier" in frame.columns else 0
    print(class_name)
    print(class_inventory.to_string(index=False))
    print(f"aligned rows: {int(len(frame))}; unresolved: {unresolved}")
    return class_inventory


run_id = datetime.now(UTC).strftime("%Y%m%dT%H%M%SZ")
repo_root

WindowsPath('c:/workspace/git/borgnetzwerk/speaker-mining')

In [2]:
from process.entity_disambiguation.io_staging import stage_inputs

staging_manifest = stage_inputs()
staging_manifest

,logical_name,source_path,staged_path,staged_filename,size_bytes
0,fs_episode_broadcasts,data/20_candidate_generation/fernsehserien_de/...,data/31_entity_disambiguation/raw_import/fs_ep...,fs_episode_broadcasts__episode_broadcasts_norm...,4121814
1,fs_episode_guests,data/20_candidate_generation/fernsehserien_de/...,data/31_entity_disambiguation/raw_import/fs_ep...,fs_episode_guests__episode_guests_normalized.csv,9097793
2,fs_episode_metadata,data/20_candidate_generation/fernsehserien_de/...,data/31_entity_disambiguation/raw_import/fs_ep...,fs_episode_metadata__episode_metadata_normaliz...,1580727
3,setup_broadcasting_programs,data/00_setup/broadcasting_programs.csv,data/31_entity_disambiguation/raw_import/setup...,setup_broadcasting_programs__broadcasting_prog...,895
4,wikidata_aliases_de,data/20_candidate_generation/wikidata/projecti...,data/31_entity_disambiguation/raw_import/wikid...,wikidata_aliases_de__aliases_de.csv,536204
5,wikidata_aliases_en,data/20_candidate_generation/wikidata/projecti...,data/31_entity_disambiguation/raw_import/wikid...,wikidata_aliases_en__aliases_en.csv,1068314
6,wikidata_classes,data/20_candidate_generation/wikidata/projecti...,data/31_entity_disambiguation/raw_import/wikid...,wikidata_classes__classes.csv,2368201
7,wikidata_episodes,data/20_candidate_generation/wikidata/projecti...,data/31_entity_disambiguation/raw_import/wikid...,wikidata_episodes__core_episodes.json,32664222
8,wikidata_organizations,data/20_candidate_generation/wikidata/projecti...,data/31_entity_disambiguation/raw_import/wikid...,wikidata_organizations__core_organizations.json,229130308
9,wikidata_persons,data/20_candidate_generation/wikidata/projecti...,data/31_entity_disambiguation/raw_import/wikid...,wikidata_persons__core_persons.json,48470801
10,wikidata_programs,data/20_candidate_generation/wikidata/projecti...,data/31_entity_disambiguation/raw_import/wikid...,wikidata_programs__core_broadcasting_programs....,219382
11,wikidata_properties,data/20_candidate_generation/wikidata/projecti...,data/31_entity_disambiguation/raw_import/wikid...,wikidata_properties__properties.csv,680889
12,wikidata_roles,data/20_candidate_generation/wikidata/projecti...,data/31_entity_disambiguation/raw_import/wikid...,wikidata_roles__core_roles.json,2
13,wikidata_series,data/20_candidate_generation/wikidata/projecti...,data/31_entity_disambiguation/raw_import/wikid...,wikidata_series__core_series.json,19570484
14,wikidata_topics,data/20_candidate_generation/wikidata/projecti...,data/31_entity_disambiguation/raw_import/wikid...,wikidata_topics__core_topics.json,417053
15,wikidata_triples,data/20_candidate_generation/wikidata/projecti...,data/31_entity_disambiguation/raw_import/wikid...,wikidata_triples__triples.csv,29064593
16,zdf_episodes,data/10_mention_detection/episodes.csv,data/31_entity_disambiguation/raw_import/zdf_e...,zdf_episodes__episodes.csv,2087215
17,zdf_persons,data/10_mention_detection/persons.csv,data/31_entity_disambiguation/raw_import/zdf_p...,zdf_persons__persons.csv,12126294
18,zdf_publications,data/10_mention_detection/publications.csv,data/31_entity_disambiguation/raw_import/zdf_p...,zdf_publications__publications.csv,325107
19,zdf_seasons,data/10_mention_detection/seasons.csv,data/31_entity_disambiguation/raw_import/zdf_s...,zdf_seasons__seasons.csv,1219
20,zdf_topics,data/10_mention_detection/topics.csv,data/31_entity_disambiguation/raw_import/zdf_t...,zdf_topics__topics.csv,14408932

In [3]:
source_inventory = build_source_inventory_report().set_index("source_name")
source_inventory

,source_kind,instances,properties,property_summary,source_path
source_name,,,,,
fs_episode_broadcasts,csv,15929,17,"fernsehserien_de_id, program_name, episode_url...",data/20_candidate_generation/fernsehserien_de/...
fs_episode_guests,csv,25452,13,"fernsehserien_de_id, program_name, episode_url...",data/20_candidate_generation/fernsehserien_de/...
fs_episode_metadata,csv,6459,13,"fernsehserien_de_id, program_name, episode_url...",data/20_candidate_generation/fernsehserien_de/...
setup_broadcasting_programs,csv,15,10,"wikibase_id, filename, label, description, ali...",data/00_setup/broadcasting_programs.csv
wikidata_aliases_de,csv,21964,2,"alias, qid",data/20_candidate_generation/wikidata/projecti...
wikidata_aliases_en,csv,39742,2,"alias, qid",data/20_candidate_generation/wikidata/projecti...
wikidata_classes,csv,8221,12,"id, class_filename, label_en, label_de, descri...",data/20_candidate_generation/wikidata/projecti...
wikidata_episodes,json,1647,70,"P1040, P11460, P1191, P12559, P1343, P136, P13...",data/20_candidate_generation/wikidata/projecti...
wikidata_organizations,json,251,1214,"P10, P1001, P10035, P1004, P10046, P1005, P100...",data/20_candidate_generation/wikidata/projecti...
wikidata_persons,json,673,805,"P10, P10021, P1003, P1005, P1006, P10069, P101...",data/20_candidate_generation/wikidata/projecti...
wikidata_programs,json,20,66,"P1019, P10286, P1113, P11245, P1132, P11740, P...",data/20_candidate_generation/wikidata/projecti...
wikidata_properties,csv,2324,7,"id, label_de, label_en, description_de, descri...",data/20_candidate_generation/wikidata/projecti...
wikidata_roles,json,0,0,,data/20_candidate_generation/wikidata/projecti...
wikidata_series,json,638,576,"P10, P1004, P10046, P1005, P101, P10106, P1015...",data/20_candidate_generation/wikidata/projecti...
wikidata_topics,json,2,101,"P10, P1036, P10767, P10804, P11137, P1120, P11...",data/20_candidate_generation/wikidata/projecti...
wikidata_triples,csv,382400,5,"subject, predicate, object, discovered_at_utc,...",data/20_candidate_generation/wikidata/projecti...
zdf_episodes,csv,2036,14,"episode_id, sendungstitel, publikation_id, pub...",data/10_mention_detection/episodes.csv
zdf_persons,csv,10390,10,"mention_id, episode_id, name, mention_category...",data/10_mention_detection/persons.csv
zdf_publications,csv,2542,11,"publikation_id, episode_id, publication_index,...",data/10_mention_detection/publications.csv
zdf_seasons,csv,17,5,"season_id, season_label, start_time, end_time,...",data/10_mention_detection/seasons.csv
zdf_topics,csv,10699,8,"mention_id, episode_id, topic, source_text, so...",data/10_mention_detection/topics.csv

## Phase 2: Value Normalization
Normalize source values before matching so later phases can reason over stable text, dates, and identifiers.

In [4]:
from process.entity_disambiguation.normalization import normalize_inputs

normalized = normalize_inputs()
{key: df.shape for key, df in normalized.items()}

{'setup_broadcasting_programs': (15, 20),
 'zdf_episodes': (2036, 29),
 'zdf_persons': (10390, 20),
 'zdf_topics': (10699, 16),
 'zdf_publications': (2542, 23),
 'zdf_seasons': (17, 12),
 'fs_episode_metadata': (6459, 27),
 'fs_episode_broadcasts': (15929, 36),
 'fs_episode_guests': (25452, 26),
 'wikidata_programs': (20, 191),
 'wikidata_series': (638, 3917),
 'wikidata_episodes': (1647, 307),
 'wikidata_persons': (673, 2697),
 'wikidata_topics': (2, 517),
 'wikidata_roles': (0, 0),
 'wikidata_organizations': (251, 12719)}

## Phase 3: Schema Harmonization
Map source properties to canonical columns and persist the schema contract for later alignment.

In [5]:
from process.entity_disambiguation.schema_mapping import write_schema_mapping

schema_mapping = write_schema_mapping(normalized)
schema_mapping

,source_name,source_column,canonical_column,mapping_strategy
0,fs_episode_broadcasts,broadcast_broadcaster,broadcast_broadcaster,direct
1,fs_episode_broadcasts,broadcast_broadcaster_key,broadcast_broadcaster_key,direct
2,fs_episode_broadcasts,broadcast_broadcaster_key_norm,broadcast_broadcaster_key_norm,direct
3,fs_episode_broadcasts,broadcast_broadcaster_norm,broadcast_broadcaster_norm,direct
4,fs_episode_broadcasts,broadcast_date,broadcast_date,direct
...,...,...,...,...
20580,zdf_topics,source_context_norm,source_context_norm,direct
20581,zdf_topics,source_text,source_text,direct
20582,zdf_topics,source_text_norm,source_text_norm,direct
20583,zdf_topics,topic,topic,direct
20584,zdf_topics,topic_norm,topic_norm,direct

## Phase 4: Layered Alignment and Persistence
Build the aligned tables, write the artifacts, and emit one-record examples for each written file.

In [6]:
import json

from pathlib import Path

from process.io_guardrails import atomic_write_csv, atomic_write_text
from process.entity_disambiguation.contracts import LAYERED_EXAMPLES_DIR, NORMALIZED_EXAMPLES_DIR, OUTPUT_FILES, RAW_EXAMPLES_DIR, SCHEMA_EXAMPLES_DIR
from process.entity_disambiguation.evidence import combine_evidence_rows
from process.entity_disambiguation.episode_alignment import build_aligned_episodes
from process.entity_disambiguation.orchestrator import _build_aligned_broadcasting_programs, _build_aligned_seasons
from process.entity_disambiguation.person_alignment import build_aligned_persons
from process.entity_disambiguation.role_org_alignment import build_aligned_organizations, build_aligned_roles
from process.entity_disambiguation.topic_alignment import build_aligned_topics

In [7]:
aligned_broadcasting_programs = _build_aligned_broadcasting_programs(normalized)
atomic_write_csv(OUTPUT_FILES["aligned_broadcasting_programs"], aligned_broadcasting_programs, index=False)
write_example(aligned_broadcasting_programs, LAYERED_EXAMPLES_DIR / "aligned_broadcasting_programs.example.csv")

broadcasting_program_inventory = print_alignment_progress("broadcasting_programs", aligned_broadcasting_programs)
broadcasting_program_evidence = [
    {
        "alignment_unit_id": str(row["alignment_unit_id"]),
        "entity_class": "broadcasting_program",
        "match_strategy": str(row["match_strategy"]),
        "match_tier": str(row["match_tier"]),
        "match_confidence": float(row["match_confidence"]),
        "evidence_summary": str(row["evidence_summary"]),
        "unresolved_reason_code": str(row["unresolved_reason_code"]),
    }
    for _, row in aligned_broadcasting_programs.iterrows()
]
len(aligned_broadcasting_programs)
aligned_broadcasting_programs

broadcasting_programs
          source instances properties
           setup        15         10
        wikidata        20         66
fernsehserien_de      n.a.       n.a.
aligned rows: 35; unresolved: 35

,alignment_unit_id,wikidata_id,fernsehserien_de_id,mention_id,canonical_label,open_refine_name,entity_class,match_confidence,match_tier,match_strategy,...,genre_(P136)_3_wikidata,named_after_(P138)_1_wikidata,named_after_(P138)_2_wikidata,MusicBrainz_series_ID_(P1407)_wikidata,based_on_(P144)_1_wikidata,based_on_(P144)_2_wikidata,title_(P1476)_wikidata,logo_image_(P154)_wikidata,follows_(P155)_wikidata,followed_by_(P156)_wikidata
0,broadcasting_program_wd_e62a307983ba,Q26878003,,,Alles in Butter,,broadcasting_program,0.0,unresolved,wikidata_program_only_baseline,...,,,,,,,,,,
1,caren_miosga,Q122961070,caren-miosga,,Caren Miosga,,broadcasting_program,0.0,unresolved,setup_program_only_baseline,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,broadcasting_program_wd_92058d199025,Q107510985,,,Danton's death,,broadcasting_program,0.0,unresolved,wikidata_program_only_baseline,...,,,,,Q920590,Q107511006,Danton's death,,,
3,der_internationale_frueshoppen,Q1194569,internationaler-fruehschoppen,,Der Internationale Frühschoppen,,broadcasting_program,0.0,unresolved,setup_program_only_baseline,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,broadcasting_program_wd_bc9a735559e6,Q1204467,,,Deutsche Vorentscheidung zum Eurovision Song C...,,broadcasting_program,0.0,unresolved,wikidata_program_only_baseline,...,,,,,,,,,Q5552115,Q828299
5,broadcasting_program_wd_38b04bff457c,Q1204469,,,Deutsche Vorentscheidung zum Eurovision Song C...,,broadcasting_program,0.0,unresolved,wikidata_program_only_baseline,...,,,,,,,,,Q5552147,Q1204474
6,broadcasting_program_wd_4e72071138f6,Q107296606,,,Deutsche Vorentscheidung zum Eurovision Song C...,,broadcasting_program,0.0,unresolved,wikidata_program_only_baseline,...,,,,,,,,,,
7,broadcasting_program_wd_b1309182cb75,Q109241979,,,Die Dilettanten des Wunders oder Die billige E...,,broadcasting_program,0.0,unresolved,wikidata_program_only_baseline,...,,,,,Q30134038,,Die Dilettanten des Wunders oder Die billige E...,,,
8,broadcasting_program_wd_629016aa7597,Q113137618,,,Die Sonntagsshow,,broadcasting_program,0.0,unresolved,wikidata_program_only_baseline,...,,,,,,,,,,
9,broadcasting_program_wd_f4e5914da14c,Q109133251,,,Die deutsche Stimme 2003,,broadcasting_program,0.0,unresolved,wikidata_program_only_baseline,...,,,,,,,,,,
10,broadcasting_program_wd_5b4cf970e261,Q1571810,,,Hallo Ü-Wagen,,broadcasting_program,0.0,unresolved,wikidata_program_only_baseline,...,,,,,,,,,,
11,broadcasting_program_wd_3562651ee10d,Q110137730,,,Hand Drauf,,broadcasting_program,0.0,unresolved,wikidata_program_only_baseline,...,,,,,,,,,,
12,hart_aber_fair,Q1587023,hart-aber-fair,,Hart aber fair,,broadcasting_program,0.0,unresolved,setup_program_only_baseline,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,broadcasting_program_wd_9789d34f57bf,Q106648083,,,Isabella von Ägypten,,broadcasting_program,0.0,unresolved,wikidata_program_only_baseline,...,,,,,Q35783041,Q106648099,,,,
14,broadcasting_program_wd_078dd40981e6,Q121339233,,,Lanz & Precht,,broadcasting_program,0.0,unresolved,wikidata_program_only_baseline,...,Q106625351,Q43773,Q44040,4cee6dae-5fe6-4202-8f16-5a7c1720f95c,,,,,,
15,lanz_und_precht,Q121339233,NONE,,Lanz und Precht,,broadcasting_program,0.0,unresolved,setup_program_only_baseline,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,maischberger,Q1330010,maischberger-ard,,Maischberger,,broadcasting_program,0.0,unresolved,setup_program_only_baseline,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,markus_lanz,Q1499182,markus-lanz,,Markus Lanz,,broadcasting_program,0.0,unresolved,setup_program_only_baseline,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,broadcasting_program_wd_e535de213109,Q1269988,,,MausLive,,broadcasting_program,0.0,unresolved,wikidata_program_only_baseline,...,,,,,,,,,,
19,maybrit_illner,Q1914407,maybrit-illner,,Maybrit Illner,,broadcasting_program,0.0,unresolved,setup_program_only_baseline,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,broadcasting_program_wd_20c07a0e7416,Q1234602,,,Monitor,,broadcasting_program,0.0,unresolved,wikidata_program_only_baseline,...,,,,,,,,Monitor logo.svg,,
21,broadcasting_program_wd_7c8b845acbef,Q110147834,,,NBA Overtime,,broadcasting_program,0.0,unresolved,wikidata_program_only_baseline,...,,,,,,,,,,
22,phoenix_runde,Q996534,phoenix-runde,,Phoenix Runde,,broadcasting_program,0.0,unresolved,setup_program_only_baseline,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,precht,Q15840908,precht,,Precht,,broadcasting_program,0.0,unresolved,setup_program_only_baseline,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,presseclub,Q2108918,presseclub,,Presseclub,,broadcasting_program,0.0,unresolved,setup_program_only_baseline,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,broadcasting_program_wd_08fe3bcda1c3,Q137807876,,,Satire Deluxe,,broadcasting_program,0.0,unresolved,wikidata_program_only_baseline,...,,,,,,,,,,
26,broadcasting_program_wd_35bb57c020ef,Q121734744,,,Scala,,broadcasting_program,0.0,unresolved,wikidata_program_only_baseline,...,,,,,,,,,,
27,startalk,Q18003196,startalk,,StarTalk,,broadcasting_program,0.0,unresolved,setup_program_only_baseline,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,unbouble,,NONE,,Unbouble,,broadcasting_program,0.0,unresolved,setup_program_only_baseline,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,broadcasting_program_wd_bd4f19ca2be4,Q110681347,,,Unwiederbringlich,,broadcasting_program,0.0,unresolved,wikidata_program_only_baseline,...,,,,,Q2499503,Q110681353,Unwiederbringlich,,,
30,wtf_talk,,NONE,,WTF talk,,broadcasting_program,0.0,unresolved,setup_program_only_baseline,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,broadcasting_program_wd_3e316f68f8ae,Q185015,,,ZeitZeichen,,broadcasting_program,0.0,unresolved,wikidata_program_only_baseline,...,,,,,,,ZeitZeichen,,,
32,couchwissen,,couchwissen,,couchwissen,,broadcasting_program,0.0,unresolved,setup_program_only_baseline,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,broadcasting_program_wd_7a23347bf790,Q1204476,,,deutsche Vorentscheidung zum Eurovision Song C...,,broadcasting_program,0.0,unresolved,wikidata_program_only_baseline,...,,,,,,,,,Q5552133,Q5552135
34,scobel,Q2260420,scobel,,scobel,,broadcasting_program,0.0,unresolved,setup_program_only_baseline,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
aligned_seasons = _build_aligned_seasons(normalized)
atomic_write_csv(OUTPUT_FILES["aligned_seasons"], aligned_seasons, index=False)
write_example(aligned_seasons, LAYERED_EXAMPLES_DIR / "aligned_seasons.example.csv")

seasons_inventory = print_alignment_progress("seasons", aligned_seasons)
season_evidence = []
for _, row in aligned_seasons.iterrows():
    season_evidence.append(
        {
            "alignment_unit_id": str(row.get("alignment_unit_id", "")),
            "entity_class": "season",
            "match_strategy": str(row.get("match_strategy", "")),
            "match_tier": str(row.get("match_tier", "")),
            "match_confidence": float(row.get("match_confidence", 0.0) or 0.0),
            "evidence_summary": str(row.get("evidence_summary", "")),
            "unresolved_reason_code": str(row.get("unresolved_reason_code", "")),
        }
    )
len(aligned_seasons)
aligned_seasons

seasons
          source instances properties
     zdf_archive        17          5
        wikidata       638        576
fernsehserien_de      n.a.       n.a.
aligned rows: 649; unresolved: 643

,alignment_unit_id,wikidata_id,fernsehserien_de_id,mention_id,canonical_label,open_refine_name,entity_class,match_confidence,match_tier,match_strategy,...,Kinobaza_film_ID_(P10167)_wikidata,Vatican_Library_ID_(former_scheme)_(P1017)_wikidata,web_feed_URL_(P1019)_1_wikidata,web_feed_URL_(P1019)_2_wikidata,Comparably_company_ID_(P10206)_wikidata,Listen_Notes_podcast_ID_(P10213)_wikidata,Oslo_Byleksikon_article_ID_(P10217)_wikidata,National_Library_of_Ireland_ID_(P10227)_wikidata,Der_Spiegel_topic_ID_(P10234)_wikidata,kino_teatr_ru_film_ID_(P10269)_wikidata
0,season_wd_22a5087aa679,Q107310112,,,#rosenfeld/feldenkirchen,,season,0.0,unresolved,wikidata_series_only_baseline,...,,,,,,,,,,
1,season_wd_7123e50e5f05,Q88082409,,,2020 COVID-19 pandemic in Akrotiri and Dhekelia,,season,0.0,unresolved,wikidata_series_only_baseline,...,,,,,,,,,,
2,season_wd_d62f374c5dcc,Q89923910,,,2020 COVID-19 pandemic in Easter Island,,season,0.0,unresolved,wikidata_series_only_baseline,...,,,,,,,,,,
3,season_wd_96bd9c7d3541,Q87769115,,,2020 COVID-19 pandemic in Guam,,season,0.0,unresolved,wikidata_series_only_baseline,...,,,,,,,,,,
4,season_wd_d5230d5e7890,Q87739744,,,2020 COVID-19 pandemic in Guernsey,,season,0.0,unresolved,wikidata_series_only_baseline,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
644,season_wd_9f428210d4f6,Q15805203,,,phoenix der tag,,season,0.0,unresolved,wikidata_series_only_baseline,...,,,,,,,,,,
645,season_wd_1a62e23a8db7,Q108736052,,,phoenix ländersache,,season,0.0,unresolved,wikidata_series_only_baseline,...,,,,,,,,,,
646,season_wd_88ff859150e8,Q996534,,,phoenix runde,,season,0.0,unresolved,wikidata_series_only_baseline,...,,,,,,,,,,
647,season_wd_4cfa737b0962,Q15853182,,,phoenix vor ort,,season,0.0,unresolved,wikidata_series_only_baseline,...,,,,,,,,,,
648,season_wd_a563332634c1,Q2260420,,,scobel,,season,0.0,unresolved,wikidata_series_only_baseline,...,,,,,,,,,,

In [9]:
aligned_episodes, episode_evidence = build_aligned_episodes(normalized)
atomic_write_csv(OUTPUT_FILES["aligned_episodes"], aligned_episodes, index=False)
write_example(aligned_episodes, LAYERED_EXAMPLES_DIR / "aligned_episodes.example.csv")
episodes_inventory = print_alignment_progress("episodes", aligned_episodes)
aligned_episodes

episodes
          source  instances  properties
     zdf_archive       2036          14
        wikidata       1647          70
fernsehserien_de       6459          13
aligned rows: 6849; unresolved: 4176

,alignment_unit_id,wikidata_id,fernsehserien_de_id,mention_id,canonical_label,open_refine_name,entity_class,match_confidence,match_tier,match_strategy,...,source_event_sequence_fernsehserien_de,premiere_date_date_fernsehserien_de,guest_1_name_fernsehserien_de,guest_1_role_fernsehserien_de,broadcast_1_date_fernsehserien_de,broadcast_1_start_time_fernsehserien_de,broadcast_1_end_date_fernsehserien_de,broadcast_1_end_time_fernsehserien_de,broadcast_1_broadcaster_fernsehserien_de,broadcast_1_is_premiere_fernsehserien_de
0,episode_fs_16a942a51c1e,,https://www.fernsehserien.de/startalk/folgen/3...,,(Alan Alda),,episode,0.00,unresolved,fs_episode_only_baseline,...,118414,2018-01-07 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,episode_fs_c15149021c90,,https://www.fernsehserien.de/startalk/folgen/3...,,(Astronaut Scott Kelly),,episode,0.00,unresolved,fs_episode_only_baseline,...,118420,2018-02-25 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,episode_fs_e8815e6e709b,,https://www.fernsehserien.de/startalk/folgen/3...,,(Celestial Navigation),,episode,0.00,unresolved,fs_episode_only_baseline,...,118411,2017-12-03 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,episode_fs_ea284b839033,,https://www.fernsehserien.de/startalk/folgen/3...,,(Frank Oz And The Science Of Puppeteering),,episode,0.00,unresolved,fs_episode_only_baseline,...,118418,2018-02-04 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,episode_fs_f3de4a50234e,,https://www.fernsehserien.de/startalk/folgen/3...,,(Interstellar Space Travel),,episode,0.00,unresolved,fs_episode_only_baseline,...,118413,2017-12-17 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6844,ep_1afa2f860c7a,,https://www.fernsehserien.de/markus-lanz/folge...,,Markus Lanz 31.10.2013,,episode,0.92,high,date_backbone_plus_title_signals,...,10530,2013-10-31 00:00:00,NaN,NaN,2013-11-06,10:15,2013-11-06,11:30,3sat,False
6845,ep_7534721383ef,Q58023746,https://www.fernsehserien.de/markus-lanz/folge...,,Markus Lanz 31.10.2018,,episode,0.92,high,date_backbone_plus_title_signals,...,42862,2018-10-31 00:00:00,Markus Lanz,Moderation,2018-10-31,23:15,2018-11-01,00:30,ZDF,True
6846,ep_eee97813e1b0,Q73248582,https://www.fernsehserien.de/markus-lanz/folge...,,Markus Lanz 31.10.2019,,episode,0.92,high,date_backbone_plus_title_signals,...,42735,2019-10-31 00:00:00,Markus Lanz,Moderation,2019-11-08,10:16,2019-11-08,11:31,3sat,False
6847,ep_cbdca5eb76ee,Q133055275,https://www.fernsehserien.de/markus-lanz/folge...,,Markus Lanz 31.10.2023,,episode,0.92,high,date_backbone_plus_title_signals,...,10520,2023-10-31 00:00:00,Markus Lanz,Moderation,2023-10-31,23:45,2023-11-01,01:00,ZDF,True
6848,ep_56eddbf7f6eb,Q130745401,https://www.fernsehserien.de/markus-lanz/folge...,,Markus Lanz 31.10.2024,,episode,0.92,high,date_backbone_plus_title_signals,...,10404,2024-10-31 00:00:00,Markus Lanz,Moderation,2024-10-31,23:20,2024-11-01,00:35,ZDF,True

In [10]:
aligned_persons, person_evidence = build_aligned_persons(normalized, aligned_episodes)
atomic_write_csv(OUTPUT_FILES["aligned_persons"], aligned_persons, index=False)
write_example(aligned_persons, LAYERED_EXAMPLES_DIR / "aligned_persons.example.csv")
persons_inventory = print_alignment_progress("persons", aligned_persons)
aligned_persons

persons
          source  instances  properties
     zdf_archive      10390          10
        wikidata        673         805
fernsehserien_de      25452          13
aligned rows: 31165; unresolved: 25368

,alignment_unit_id,wikidata_id,fernsehserien_de_id,mention_id,canonical_label,open_refine_name,entity_class,match_confidence,match_tier,match_strategy,...,guest_description_fernsehserien_de,guest_url_fernsehserien_de,guest_image_url_fernsehserien_de,guest_order_fernsehserien_de,normalized_at_utc_fernsehserien_de,normalizer_rule_fernsehserien_de,source_discovered_sequence_fernsehserien_de,source_event_sequence_fernsehserien_de,entity_id_wikidata,entity_type_wikidata
0,person_fs_01c500a253e0,,https://www.fernsehserien.de/internationaler-f...,,-Andrej Gurkov,Andrej Gurkov,person,0.0,unresolved,fernsehserien_guest_only_baseline,...,Russland,https://www.fernsehserien.de/andrej-gurkov/fil...,https://bilder.fernsehserien.de/fernsehserien....,3,2026-04-09T09:55:55Z,episode_guest_norm_v1,108562,127552,NaN,NaN
1,person_fs_1ff4ae2b3b83,,https://www.fernsehserien.de/internationaler-f...,,-Andrej Gurkov,Andrej Gurkov,person,0.0,unresolved,fernsehserien_guest_only_baseline,...,Russland,https://www.fernsehserien.de/andrej-gurkov/fil...,https://bilder.fernsehserien.de/fernsehserien....,2,2026-04-09T09:55:55Z,episode_guest_norm_v1,107041,126922,NaN,NaN
2,person_fs_3be675a4028c,,https://www.fernsehserien.de/internationaler-f...,,-Andrej Gurkov,Andrej Gurkov,person,0.0,unresolved,fernsehserien_guest_only_baseline,...,Russland,https://www.fernsehserien.de/andrej-gurkov/fil...,https://bilder.fernsehserien.de/fernsehserien....,2,2026-04-09T09:55:55Z,episode_guest_norm_v1,108454,127505,NaN,NaN
3,person_fs_c1c74211a544,,https://www.fernsehserien.de/internationaler-f...,,-Andrej Gurkov,Andrej Gurkov,person,0.0,unresolved,fernsehserien_guest_only_baseline,...,Russland,https://www.fernsehserien.de/andrej-gurkov/fil...,https://bilder.fernsehserien.de/fernsehserien....,3,2026-04-09T09:55:55Z,episode_guest_norm_v1,106952,126890,NaN,NaN
4,person_fs_38e45b8baae3,,https://www.fernsehserien.de/internationaler-f...,,-Andrew Denison,Andrew Denison,person,0.0,unresolved,fernsehserien_guest_only_baseline,...,USA,https://www.fernsehserien.de/andrew-denison/fi...,https://bilder.fernsehserien.de/fernsehserien....,1,2026-04-09T09:55:55Z,episode_guest_norm_v1,108453,127504,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31160,person_fs_6f391361c4cf,,https://www.fernsehserien.de/markus-lanz/folge...,,„Ingrid,„Ingrid,person,0.0,unresolved,fernsehserien_guest_only_baseline,...,,https://www.fernsehserien.de/ingrid-2/filmografie,https://bilder.fernsehserien.de/fernsehserien....,4,2026-04-08T13:59:55Z,episode_guest_norm_v1,7174,13770,NaN,NaN
31161,person_fs_c184f2ef3201,,https://www.fernsehserien.de/markus-lanz/folge...,,„Onkel Fisch“,„Onkel Fisch“,person,0.0,unresolved,fernsehserien_guest_only_baseline,...,Kabarettisten-Duo,https://www.fernsehserien.de/onkel-fisch/filmo...,https://bilder.fernsehserien.de/fernsehserien....,2,2026-04-08T16:32:06Z,episode_guest_norm_v1,27067,31935,NaN,NaN
31162,person_fs_0b08a9ddca86,,https://www.fernsehserien.de/maischberger-ard/...,,„Süddeutsche Zeitung“,„Süddeutsche Zeitung“,person,0.0,unresolved,fernsehserien_guest_only_baseline,...,,https://www.fernsehserien.de/sueddeutsche-zeit...,https://bilder.fernsehserien.de/fernsehserien....,13,2026-04-09T08:21:58Z,episode_guest_norm_v1,80280,85738,NaN,NaN
31163,person_fs_44e504929a81,,https://www.fernsehserien.de/markus-lanz/folge...,,„The Boss Hoss“,„The Boss Hoss“,person,0.0,unresolved,fernsehserien_guest_only_baseline,...,Musiker,https://www.fernsehserien.de/the-boss-hoss-2/f...,https://bilder.fernsehserien.de/fernsehserien....,2,2026-04-08T16:26:09Z,episode_guest_norm_v1,22141,29397,NaN,NaN
31164,person_fs_66abbfbcd076,,https://www.fernsehserien.de/markus-lanz/folge...,,„Zola“,„Zola“,person,0.0,unresolved,fernsehserien_guest_only_baseline,...,Krankenschwester,https://www.fernsehserien.de/zola-2/filmografie,https://bilder.fernsehserien.de/fernsehserien....,3,2026-04-08T16:23:43Z,episode_guest_norm_v1,19616,28290,NaN,NaN

In [11]:
aligned_topics, topic_evidence = build_aligned_topics(normalized)
atomic_write_csv(OUTPUT_FILES["aligned_topics"], aligned_topics, index=False)
write_example(aligned_topics, LAYERED_EXAMPLES_DIR / "aligned_topics.example.csv")
topics_inventory = print_alignment_progress("topics", aligned_topics)
aligned_topics

topics
          source instances properties
     zdf_archive     10699          8
        wikidata         2        101
fernsehserien_de      n.a.       n.a.
aligned rows: 10701; unresolved: 10701

,alignment_unit_id,wikidata_id,fernsehserien_de_id,mention_id,canonical_label,open_refine_name,entity_class,match_confidence,match_tier,match_strategy,...,video_(P10)_4_wikidata,video_(P10)_5_wikidata,video_(P10)_6_wikidata,Dewey_Decimal_Classification_(P1036)_wikidata,X_moment_ID_(P10767)_1_wikidata,X_moment_ID_(P10767)_2_wikidata,X_list_ID_(P10804)_wikidata,Reddit_topic_ID_(P11137)_wikidata,number_of_deaths_(P1120)_1_wikidata,number_of_deaths_(P1120)_2_wikidata
0,tm_e4072dc25a3a,,,tm_e4072dc25a3a,"""Anden-Pakt"" und kommender Bundesparteitag der...",,topic,0.0,unresolved,topic_context_only_best_effort,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,tm_f9706e317063,,,tm_f9706e317063,"""Böblinger Modell"": Erfahrungen mit der Einfüh...",,topic,0.0,unresolved,topic_context_only_best_effort,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,tm_2c1fdf567220,,,tm_2c1fdf567220,"""D-Day-Affäre""",,topic,0.0,unresolved,topic_context_only_best_effort,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,tm_cd7acf5c7dde,,,tm_cd7acf5c7dde,"""Das Wunder von der Grotenburg"" im Jahr 1986. ...",,topic,0.0,unresolved,topic_context_only_best_effort,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,tm_d40cb3cd03f8,,,tm_d40cb3cd03f8,"""Diät"" von Bernd Stelter",,topic,0.0,unresolved,topic_context_only_best_effort,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10696,tm_d0deb8343a41,,,tm_d0deb8343a41,übertriebene Falschdarstellung Deutschlands vo...,,topic,0.0,unresolved,topic_context_only_best_effort,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10697,tm_f21e94f3d442,,,tm_f21e94f3d442,überweisen wenn man dieses versteuert,,topic,0.0,unresolved,topic_context_only_best_effort,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10698,tm_116a078f6703,,,tm_116a078f6703,"überwinden, sein Buch ""Die Frau in mir - Ein M...",,topic,0.0,unresolved,topic_context_only_best_effort,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10699,tm_27dd604417f0,,,tm_27dd604417f0,"„Taurus""-Abhöraffäre",,topic,0.0,unresolved,topic_context_only_best_effort,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10700,tm_ea9c0bb0f16d,,,tm_ea9c0bb0f16d,„Taurus“-Waffenlieferung an die Ukraine sowie ...,,topic,0.0,unresolved,topic_context_only_best_effort,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
aligned_roles, role_evidence = build_aligned_roles(normalized)
atomic_write_csv(OUTPUT_FILES["aligned_roles"], aligned_roles, index=False)
write_example(aligned_roles, LAYERED_EXAMPLES_DIR / "aligned_roles.example.csv")
roles_inventory = print_alignment_progress("roles", aligned_roles)
aligned_roles

roles
          source instances properties
     zdf_archive     10390         10
        wikidata         0          0
fernsehserien_de      n.a.       n.a.
aligned rows: 9625; unresolved: 9625

,alignment_unit_id,wikidata_id,fernsehserien_de_id,mention_id,canonical_label,open_refine_name,entity_class,match_confidence,match_tier,match_strategy,...,mention_id_zdf,episode_id_zdf,name_zdf,mention_category_zdf,beschreibung_zdf,source_text_zdf,source_context_zdf,parsing_rule_zdf,confidence_zdf,confidence_note_zdf
0,role_1a7f50ffaa77,,,pm_16b927e315b2,"""...und Tschüss""",,role,0.0,unresolved,description_role_extraction_best_effort,...,pm_16b927e315b2,ep_4860ca2e1d24,Angela Merkel,guest,"""...und Tschüss""",über Nachfolge von BK Angela Merkel als Partei...,"den Studiogästen Robin ALEXANDER (Journalist ""...",single_parenthetical,0.95,single name directly tied to parenthetical des...
1,role_c6e350ff69f2,,,pm_d3046c591b36,"""Ada""",,role,0.0,unresolved,description_role_extraction_best_effort,...,pm_d3046c591b36,ep_488584e0e9ec,Donald Trump,guest,"""Ada""","zur Politik von Donald Trump, zugespitztes Ges...",den Studiogästen Elmar THEVEßEN (Leiter ZDF-St...,last_name_parenthetical,0.82,description assigned to nearest name before pa...
2,role_c71734aa1bf0,,,pm_8c8d1b66dde2,"""Das rote Kleid""",,role,0.0,unresolved,description_role_extraction_best_effort,...,pm_8c8d1b66dde2,ep_e7c4cf9ebf03,KRETSCHMER,guest,"""Das rote Kleid""","die Probleme von alleinerziehenden Frauen, das...","den Studiogästen Rainer HANK (Journalist), Sar...",single_parenthetical_mononym,0.62,single-token stage or artist name tied to pare...
3,role_1ebbd6e8d2ff,,,pm_f72836b04d39,"""Der Bachelor""",,role,0.0,unresolved,description_role_extraction_best_effort,...,pm_f72836b04d39,ep_e76486da1b9c,Paul JANKE,guest,"""Der Bachelor""","Paul JANKE (""Der Bachelor"")",Studiogästen Heiner GEISSLER (GEIßLER) (ehem. ...,single_parenthetical,0.95,single name directly tied to parenthetical des...
4,role_6258a55fc7fd,,,pm_b43e79711238,"""Der Bachelor""",,role,0.0,unresolved,description_role_extraction_best_effort,...,pm_b43e79711238,ep_1bd8caacb0bc,Jan KRALITSCHKA,guest,"""Der Bachelor""","Jan KRALITSCHKA (""Der Bachelor"")",Studiogästen Markus SOEDER (Söder) (Finanzmini...,single_parenthetical,0.95,single name directly tied to parenthetical des...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9620,role_e3abefa79e16,,,pm_1fbadb7452bd,überlebte Massaker auf Festival in Israel,,role,0.0,unresolved,description_role_extraction_best_effort,...,pm_1fbadb7452bd,ep_f080cbe362aa,Laura BLAJMAN KADAR,guest,überlebte Massaker auf Festival in Israel,Laura BLAJMAN KADAR (überlebte Massaker auf Fe...,den Studiogästen Johannes THIEMANN (Weltmeiste...,single_parenthetical,0.95,single name directly tied to parenthetical des...
9621,role_3b4a4221a9e1,,,pm_d75131aa1805,überlebte den Holocaust,,role,0.0,unresolved,description_role_extraction_best_effort,...,pm_d75131aa1805,ep_0f0e3a121465,Leon WEINTRAUB,guest,überlebte den Holocaust,den Studiogästen Leon WEINTRAUB (überlebte den...,den Studiogästen Leon WEINTRAUB (überlebte den...,single_parenthetical,0.95,single name directly tied to parenthetical des...
9622,role_5a93358421fc,,,pm_bc7bcf6954df,"überlebte den Untergang der ""Estonia""",,role,0.0,unresolved,description_role_extraction_best_effort,...,pm_bc7bcf6954df,ep_50ed70dc9506,Manfred ROTHE,guest,"überlebte den Untergang der ""Estonia""","Manfred ROTHE (überlebte den Untergang der ""Es...",den Studiogästen Lothar DE MAIZIERE (Politiker...,single_parenthetical,0.95,single name directly tied to parenthetical des...
9623,role_e65999e552dc,,,pm_11e29a762af4,überlebte im Alter von 17 Jahren als Einzige e...,,role,0.0,unresolved,description_role_extraction_best_effort,...,pm_11e29a762af4,ep_d1a95a59efe7,Juliane KOEPCKE,guest,überlebte im Alter von 17 Jahren als Einzige e...,und Juliane KOEPCKE (überlebte im Alter von 17...,"den Studiogästen Dirk STEFFENS (Moderator), Ma...",single_parenthetical,0.95,single name directly tied to parenthetical des...
9624,role_c3965ef1d675,,,pm_98c6cf6afb37,überlebten die Gletscherbahn-Katastrophe von K...,,role,0.0,unresolved,description_role_extraction_best_effort,...,pm_98c6cf6afb37,ep_624f5afa2f9d,Roland MAYERHOFER,guest,überlebten die Gletscherbahn-Katastrophe von K...,Elaine MAYERHOFER und Roland MAYERHOFER (überl...,den Studiogästen Hannelore KRAFT (MPr Nordrhei...,last_name_parenthetical,0.82,description assigned to nearest name before pa...

In [13]:
aligned_organizations, organization_evidence = build_aligned_organizations(normalized)
atomic_write_csv(OUTPUT_FILES["aligned_organizations"], aligned_organizations, index=False)
write_example(aligned_organizations, LAYERED_EXAMPLES_DIR / "aligned_organizations.example.csv")
organizations_inventory = print_alignment_progress("organizations", aligned_organizations)
aligned_organizations

organizations
          source instances properties
     zdf_archive      n.a.       n.a.
        wikidata       251       1214
fernsehserien_de      n.a.       n.a.
aligned rows: 251; unresolved: 251

,alignment_unit_id,wikidata_id,fernsehserien_de_id,mention_id,canonical_label,open_refine_name,entity_class,match_confidence,match_tier,match_strategy,...,death_rate_(P10091)_2_wikidata,death_rate_(P10091)_3_wikidata,death_rate_(P10091)_4_wikidata,death_rate_(P10091)_5_wikidata,field_of_work_(P101)_1_wikidata,field_of_work_(P101)_2_wikidata,field_of_work_(P101)_3_wikidata,field_of_work_(P101)_4_wikidata,field_of_work_(P101)_5_wikidata,field_of_work_(P101)_6_wikidata
0,organization_wd_775640803911,Q229805,,,3sat,,organization,0.0,unresolved,wikidata_organization_only_baseline,...,,,,,,,,,,
1,organization_wd_fba8ba917032,Q238723,,,5. Arrondissement von Paris,,organization,0.0,unresolved,wikidata_organization_only_baseline,...,,,,,,,,,,
2,organization_wd_505c10318ff5,Q49653,,,ARD,,organization,0.0,unresolved,wikidata_organization_only_baseline,...,,,,,,,,,,
3,organization_wd_1d659acab535,Q889,,,Afghanistan,,organization,0.0,unresolved,wikidata_organization_only_baseline,...,+7.113|1,+7.344|1,+6.906|1,,,,,,,
4,organization_wd_3ab2371a353c,Q222,,,Albanien,,organization,0.0,unresolved,wikidata_organization_only_baseline,...,+10.785|1,+11.325|1,+11.194|1,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
246,organization_wd_9ffc8e7e9473,Q79,,,Ägypten,,organization,0.0,unresolved,wikidata_organization_only_baseline,...,+5.851|1,+6.327|1,+6.39|1,,,,,,,
247,organization_wd_b2d2596dcd5b,Q983,,,Äquatorialguinea,,organization,0.0,unresolved,wikidata_organization_only_baseline,...,+9.026|1,+9.042|1,+8.708|1,,,,,,,
248,organization_wd_e22bbada5962,Q115,,,Äthiopien,,organization,0.0,unresolved,wikidata_organization_only_baseline,...,+6.616|1,+6.776|1,+6.497|1,,,,,,,
249,organization_wd_371ba227ca7a,Q40,,,Österreich,,organization,0.0,unresolved,wikidata_organization_only_baseline,...,+10.3|1,+10.3|1,+10.3|1,,,,,,,
250,organization_wd_97c4d39d001c,Q262386,,,Österreichischer Rundfunk,,organization,0.0,unresolved,wikidata_organization_only_baseline,...,,,,,,,,,,

In [14]:
evidence_df = combine_evidence_rows(
    broadcasting_program_evidence,
    season_evidence,
    episode_evidence,
    person_evidence,
    topic_evidence,
    role_evidence,
    organization_evidence,
)
atomic_write_csv(OUTPUT_FILES["match_evidence"], evidence_df, index=False)

write_example(staging_manifest, RAW_EXAMPLES_DIR / "staging_manifest.example.csv")
for _, manifest_row in staging_manifest.iterrows():
    staged_path = Path(str(manifest_row.get("staged_path", "")))
    if not staged_path.exists():
        continue

    suffix = staged_path.suffix.lower()
    example_name = f"{staged_path.stem}.example{suffix}"
    example_path = RAW_EXAMPLES_DIR / example_name

    if suffix == ".csv":
        sample_df = pd.read_csv(staged_path, nrows=1, dtype=str).fillna("")
        atomic_write_csv(example_path, sample_df, index=False)
    elif suffix == ".json":
        with staged_path.open("r", encoding="utf-8") as f:
            payload = json.load(f)
        if isinstance(payload, dict):
            if payload:
                first_key = sorted(payload.keys())[0]
                sample_payload = {first_key: payload[first_key]}
            else:
                sample_payload = {}
        elif isinstance(payload, list):
            sample_payload = payload[:1]
        else:
            sample_payload = payload
        atomic_write_text(example_path, json.dumps(sample_payload, indent=2, ensure_ascii=True) + "\n")

for key, df in normalized.items():
    write_example(df, NORMALIZED_EXAMPLES_DIR / f"{key}.example.csv")
write_example(schema_mapping, SCHEMA_EXAMPLES_DIR / "source_schema_mapping.example.csv")

{
    "broadcasting_programs": len(aligned_broadcasting_programs),
    "seasons": len(aligned_seasons),
    "episodes": len(aligned_episodes),
    "persons": len(aligned_persons),
    "topics": len(aligned_topics),
    "roles": len(aligned_roles),
    "organizations": len(aligned_organizations),
    "evidence_rows": len(evidence_df),
}

{'broadcasting_programs': 35,
 'seasons': 649,
 'episodes': 6849,
 'persons': 31165,
 'topics': 10701,
 'roles': 9625,
 'organizations': 251,
 'evidence_rows': 59275}

## Phase 5: Quality Gates and Run Summary
Validate the written artifacts and persist the run summary for downstream review.

In [15]:
import json

from process.entity_disambiguation.contracts import OUTPUT_FILES
from process.entity_disambiguation.quality_gates import run_quality_gates
from process.io_guardrails import atomic_write_text

gate_report = run_quality_gates()
summary = {
    "run_id": run_id,
    "write_examples": True,
    "staged_files": int(len(staging_manifest)),
    "source_inventory": source_inventory.reset_index().to_dict(orient="records"),
    "class_source_inventory": {
        "broadcasting_programs": broadcasting_program_inventory.to_dict(orient="records"),
        "seasons": seasons_inventory.to_dict(orient="records"),
        "episodes": episodes_inventory.to_dict(orient="records"),
        "persons": persons_inventory.to_dict(orient="records"),
        "topics": topics_inventory.to_dict(orient="records"),
        "roles": roles_inventory.to_dict(orient="records"),
        "organizations": organizations_inventory.to_dict(orient="records"),
    },
    "aligned_counts": {
        "broadcasting_programs": int(len(aligned_broadcasting_programs)),
        "seasons": int(len(aligned_seasons)),
        "episodes": int(len(aligned_episodes)),
        "persons": int(len(aligned_persons)),
        "topics": int(len(aligned_topics)),
        "roles": int(len(aligned_roles)),
        "organizations": int(len(aligned_organizations)),
    },
    "unmatched_counts": {
        "broadcasting_programs": int(aligned_broadcasting_programs["match_tier"].eq("unresolved").sum()),
        "seasons": int(aligned_seasons["match_tier"].eq("unresolved").sum()),
        "episodes": int(aligned_episodes["match_tier"].eq("unresolved").sum()),
        "persons": int(aligned_persons["match_tier"].eq("unresolved").sum()),
        "topics": int(aligned_topics["match_tier"].eq("unresolved").sum()),
        "roles": int(aligned_roles["match_tier"].eq("unresolved").sum()),
        "organizations": int(aligned_organizations["match_tier"].eq("unresolved").sum()),
    },
    "quality_gates": gate_report,
}
atomic_write_text(OUTPUT_FILES["run_summary"], json.dumps(summary, indent=2, ensure_ascii=True) + "\n")
summary

{'run_id': '20260505T110537Z',
 'write_examples': True,
 'staged_files': 21,
 'source_inventory': [{'source_name': 'fs_episode_broadcasts',
   'source_kind': 'csv',
   'instances': 15929,
   'properties': 17,
   'property_summary': 'fernsehserien_de_id, program_name, episode_url, broadcast_date, broadcast_start_time, broadcast_end_date, broadcast_end_time, broadcast_timezone_offset',
   'source_path': 'data/20_candidate_generation/fernsehserien_de/projections/episode_broadcasts_normalized.csv'},
  {'source_name': 'fs_episode_guests',
   'source_kind': 'csv',
   'instances': 25452,
   'properties': 13,
   'property_summary': 'fernsehserien_de_id, program_name, episode_url, guest_name, guest_role, guest_description, guest_url, guest_image_url',
   'source_path': 'data/20_candidate_generation/fernsehserien_de/projections/episode_guests_normalized.csv'},
  {'source_name': 'fs_episode_metadata',
   'source_kind': 'csv',
   'instances': 6459,
   'properties': 13,
   'property_summary': 'fernsehserien_de_id, program_name, episode_url, episode_title, duration_minutes, description_text, description_source, premiere_date',
   'source_path': 'data/20_candidate_generation/fernsehserien_de/projections/episode_metadata_normalized.csv'},
  {'source_name': 'setup_broadcasting_programs',
   'source_kind': 'csv',
   'instances': 15,
   'properties': 10,
   'property_summary': 'wikibase_id, filename, label, description, alias, label_de, description_de, alias_de',
   'source_path': 'data/00_setup/broadcasting_programs.csv'},
  {'source_name': 'wikidata_aliases_de',
   'source_kind': 'csv',
   'instances': 21964,
   'properties': 2,
   'property_summary': 'alias, qid',
   'source_path': 'data/20_candidate_generation/wikidata/projections/archive/aliases_de.csv'},
  {'source_name': 'wikidata_aliases_en',
   'source_kind': 'csv',
   'instances': 39742,
   'properties': 2,
   'property_summary': 'alias, qid',
   'source_path': 'data/20_candidate_generation/wikidata/projections/archive/aliases_en.csv'},
  {'source_name': 'wikidata_classes',
   'source_kind': 'csv',
   'instances': 8221,
   'properties': 12,
   'property_summary': 'id, class_filename, label_en, label_de, description_en, description_de, alias_en, alias_de',
   'source_path': 'data/20_candidate_generation/wikidata/projections/archive/classes.csv'},
  {'source_name': 'wikidata_episodes',
   'source_kind': 'json',
   'instances': 1647,
   'properties': 70,
   'property_summary': 'P1040, P11460, P1191, P12559, P1343, P136, P138, P1431',
   'source_path': 'data/20_candidate_generation/wikidata/projections/archive/core_episodes.json'},
  {'source_name': 'wikidata_organizations',
   'source_kind': 'json',
   'instances': 251,
   'properties': 1214,
   'property_summary': 'P10, P1001, P10035, P1004, P10046, P1005, P10077, P10091',
   'source_path': 'data/20_candidate_generation/wikidata/projections/archive/core_organizations.json'},
  {'source_name': 'wikidata_persons',
   'source_kind': 'json',
   'instances': 673,
   'properties': 805,
   'property_summary': 'P10, P10021, P1003, P1005, P1006, P10069, P101, P1015',
   'source_path': 'data/20_candidate_generation/wikidata/projections/archive/core_persons.json'},
  {'source_name': 'wikidata_programs',
   'source_kind': 'json',
   'instances': 20,
   'properties': 66,
   'property_summary': 'P1019, P10286, P1113, P11245, P1132, P11740, P1191, P1344',
   'source_path': 'data/20_candidate_generation/wikidata/projections/archive/core_broadcasting_programs.json'},
  {'source_name': 'wikidata_properties',
   'source_kind': 'csv',
   'instances': 2324,
   'properties': 7,
   'property_summary': 'id, label_de, label_en, description_de, description_en, alias_de, alias_en',
   'source_path': 'data/20_candidate_generation/wikidata/projections/archive/properties.csv'},
  {'source_name': 'wikidata_roles',
   'source_kind': 'json',
   'instances': 0,
   'properties': 0,
   'property_summary': '',
   'source_path': 'data/20_candidate_generation/wikidata/projections/archive/core_roles.json'},
  {'source_name': 'wikidata_series',
   'source_kind': 'json',
   'instances': 638,
   'properties': 576,
   'property_summary': 'P10, P1004, P10046, P1005, P101, P10106, P1015, P10164',
   'source_path': 'data/20_candidate_generation/wikidata/projections/archive/core_series.json'},
  {'source_name': 'wikidata_topics',
   'source_kind': 'json',
   'instances': 2,
   'properties': 101,
   'property_summary': 'P10, P1036, P10767, P10804, P11137, P1120, P11408, P1151',
   'source_path': 'data/20_candidate_generation/wikidata/projections/archive/core_topics.json'},
  {'source_name': 'wikidata_triples',
   'source_kind': 'csv',
   'instances': 382400,
   'properties': 5,
   'property_summary': 'subject, predicate, object, discovered_at_utc, source_query_file',
   'source_path': 'data/20_candidate_generation/wikidata/projections/archive/triples.csv'},
  {'source_name': 'zdf_episodes',
   'source_kind': 'csv',
   'instances': 2036,
   'properties': 14,
   'property_summary': 'episode_id, sendungstitel, publikation_id, publikationsdatum, dauer, archivnummer, prod_nr_beitrag, zeit_tc_start',
   'source_path': 'data/10_mention_detection/episodes.csv'},
  {'source_name': 'zdf_persons',
   'source_kind': 'csv',
   'instances': 10390,
   'properties': 10,
   'property_summary': 'mention_id, episode_id, name, mention_category, beschreibung, source_text, source_context, parsing_rule',
   'source_path': 'data/10_mention_detection/persons.csv'},
  {'source_name': 'zdf_publications',
   'source_kind': 'csv',
   'instances': 2542,
   'properties': 11,
   'property_summary': 'publikation_id, episode_id, publication_index, date, time, duration, program, prod_nr_sendung',
   'source_path': 'data/10_mention_detection/publications.csv'},
  {'source_name': 'zdf_seasons',
   'source_kind': 'csv',
   'instances': 17,
   'properties': 5,
   'property_summary': 'season_id, season_label, start_time, end_time, episode_count',
   'source_path': 'data/10_mention_detection/seasons.csv'},
  {'source_name': 'zdf_topics',
   'source_kind': 'csv',
   'instances': 10699,
   'properties': 8,
   'property_summary': 'mention_id, episode_id, topic, source_text, source_context, parsing_rule, confidence, confidence_note',
   'source_path': 'data/10_mention_detection/topics.csv'}],
 'class_source_inventory': {'broadcasting_programs': [{'source': 'setup',
    'instances': 15,
    'properties': 10},
   {'source': 'wikidata', 'instances': 20, 'properties': 66},
   {'source': 'fernsehserien_de', 'instances': 'n.a.', 'properties': 'n.a.'}],
  'seasons': [{'source': 'zdf_archive', 'instances': 17, 'properties': 5},
   {'source': 'wikidata', 'instances': 638, 'properties': 576},
   {'source': 'fernsehserien_de', 'instances': 'n.a.', 'properties': 'n.a.'}],
  'episodes': [{'source': 'zdf_archive', 'instances': 2036, 'properties': 14},
   {'source': 'wikidata', 'instances': 1647, 'properties': 70},
   {'source': 'fernsehserien_de', 'instances': 6459, 'properties': 13}],
  'persons': [{'source': 'zdf_archive', 'instances': 10390, 'properties': 10},
   {'source': 'wikidata', 'instances': 673, 'properties': 805},
   {'source': 'fernsehserien_de', 'instances': 25452, 'properties': 13}],
  'topics': [{'source': 'zdf_archive', 'instances': 10699, 'properties': 8},
   {'source': 'wikidata', 'instances': 2, 'properties': 101},
   {'source': 'fernsehserien_de', 'instances': 'n.a.', 'properties': 'n.a.'}],
  'roles': [{'source': 'zdf_archive', 'instances': 10390, 'properties': 10},
   {'source': 'wikidata', 'instances': 0, 'properties': 0},
   {'source': 'fernsehserien_de', 'instances': 'n.a.', 'properties': 'n.a.'}],
  'organizations': [{'source': 'zdf_archive',
    'instances': 'n.a.',
    'properties': 'n.a.'},
   {'source': 'wikidata', 'instances': 251, 'properties': 1214},
   {'source': 'fernsehserien_de', 'instances': 'n.a.', 'properties': 'n.a.'}]},
 'aligned_counts': {'broadcasting_programs': 35,
  'seasons': 649,
  'episodes': 6849,
  'persons': 31165,
  'topics': 10701,
  'roles': 9625,
  'organizations': 251},
 'unmatched_counts': {'broadcasting_programs': 35,
  'seasons': 643,
  'episodes': 4176,
  'persons': 25368,
  'topics': 10701,
  'roles': 9625,
  'organizations': 251},
 'quality_gates': {'status': 'ok',
  'unresolved_rows': 50799,
  'inferred_rows': 15,
  'checked_files': 7}}